let g:floaterm_keymap_new = '<s-t>'
let g:floaterm_keymap_kill = '<s-q>'
let g:floaterm_keymap_toggle = '<Leader>ft'
let g:floaterm_keymap_show = '<Leader>fs'
let g:floaterm_keymap_hide = '<Leader>fh'
